/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visitante;

import Empresa.Controlador_Empresa;
import Empresa.Empresa;
import Empresa.Modelo_Empresa;
import Escritorio.Escritorio;
import static Escritorio.Escritorio.CentrarInternal;
import static Escritorio.Escritorio.DeskTop;
import OtrosDriver.Conexion;
import OtrosDriver.Driver;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Zuly Galicia
 */
public class Registrar_Visitante extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registrar_Visitante
     */
    public Registrar_Visitante() {

        initComponents();
        inicio();

    }
    Controlador_Empresa DE = new Controlador_Empresa();
    Controlador_Visitante DV = new Controlador_Visitante();
    ArrayList<Modelo_Empresa> mod;
    Conexion cx = new Conexion();
    Connection cn;
    Driver d = new Driver();
    Consulta_Visitante dd = new Consulta_Visitante();

    public void inicio() {
        cn = cx.Conectar();
        limpiar();
        d.OnlyDecimal(Monto);
        d.OnlyNumbers(TelefonoVisitante);
        d.OnlyLetters(NombreVisitante);
        d.OnlyLetters(ApellidoVisitante);
        Monto.setText("0");
    }

    void limpiar() {
        comboEmpresa.removeAllItems();
        Obtener_Empresa();
        NombreVisitante.setText("");
        ApellidoVisitante.setText("");
        TelefonoVisitante.setText("");
        Monto.setText("0");

    }

    void Obtener_Empresa() {
        mod = DE.Consulta_(cn);
        for (int x = 0; x < mod.size(); x++) {
            comboEmpresa.addItem(mod.get(x).getNombreEmpresa());
            Monto.setText(String.valueOf(mod.get(x).getMonto()));

        }
    }

    public void Obtener_Monto(String id) {
        mod = DE.ConsultaSaldo(id, cn);
        for (int x = 0; x < mod.size(); x++) {
            Monto.setText(String.valueOf(mod.get(x).getMonto()));

        }
    }

    void Guardar(String NombreVisitante, String Apellido, String telefono, String monto, String idUsuario, int idEmpresa, String LugarMonto, Connection cn) {
        int Telefono = Integer.parseInt(telefono);
        double Monto = Double.parseDouble(monto);
        int IDusuario = Integer.parseInt(idUsuario);

        if (NombreVisitante.equals("")) {
            JOptionPane.showMessageDialog(null, "<html><font face='Berlin Sans FB' size='6' color='094293'>¡Introduzca Nombre!</font></html>", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (Apellido.equals("")) {
            JOptionPane.showMessageDialog(null, "<html><font face='Berlin Sans FB' size='6' color='094293'>¡Introduzca Apellido!</font></html>", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (telefono.equals("")) {
            JOptionPane.showMessageDialog(null, "<html><font face='Berlin Sans FB' size='6' color='094293'>¡Introduzca Telefono!</font></html>", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
             if(DV.comparacion(""+NombreVisitante, ""+Apellido, cn)){
                   JOptionPane.showMessageDialog(null, "<html><font face='Berlin Sans FB' size='6' color='094293'>¡Este Usuario ya Existe!</font></html>", "Error", JOptionPane.WARNING_MESSAGE);
          return;
             }else{

            DV.Guardar_Visitante(NombreVisitante, Apellido, Telefono, Monto, IDusuario, idEmpresa, LugarMonto, cn);
            limpiar();
        }
        }
    }

    int IdEmpresa(int Indexx) {
        int Id;
        mod = DE.Consulta_Empresa2("", cn);
        Id = mod.get(Indexx).getId_Empresa();
        return Id;
    }

    String LugarMonto() {
        String va = "";
        if (Montos.isSelected()) {
            va = "E";//Monto de Empresa
        } else {
            va = "V";//Monto de Visitante
        }
        return va;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreVisitante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ApellidoVisitante = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TelefonoVisitante = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        BttGuardar1 = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        comboEmpresa = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        AddEmpresa = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Monto = new javax.swing.JTextField();
        Montos = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jTabbedPane1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel1.setEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setStartColor(new java.awt.Color(0, 102, 204));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Visitante");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(20, 20, 340, 41);
        kGradientPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 70, 620, 23);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Visitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre: ");

        NombreVisitante.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        NombreVisitante.setText("jTextField1");
        NombreVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreVisitanteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido: ");

        ApellidoVisitante.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        ApellidoVisitante.setText("jTextField2");

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Empresa:");

        TelefonoVisitante.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        TelefonoVisitante.setText("jTextField4");

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        BttGuardar1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        BttGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        BttGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Save_45px.png"))); // NOI18N
        BttGuardar1.setText("Guardar");
        BttGuardar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BttGuardar1.setContentAreaFilled(false);
        BttGuardar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Save_55px.png"))); // NOI18N
        BttGuardar1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Save_45px.png"))); // NOI18N
        BttGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttGuardar1ActionPerformed(evt);
            }
        });

        Limpiar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/broom_45px.png"))); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Limpiar.setContentAreaFilled(false);
        Limpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Broom_555px.png"))); // NOI18N
        Limpiar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/broom_45px.png"))); // NOI18N
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BttGuardar1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BttGuardar1)
                .addGap(18, 18, 18)
                .addComponent(Limpiar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        comboEmpresa.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        comboEmpresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEmpresaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Teléfono: ");

        AddEmpresa.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        AddEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        AddEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Add_35px.png"))); // NOI18N
        AddEmpresa.setText("Añadir empresa");
        AddEmpresa.setToolTipText("Añadir Empresa");
        AddEmpresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AddEmpresa.setContentAreaFilled(false);
        AddEmpresa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Add_45px.png"))); // NOI18N
        AddEmpresa.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Add_35px.png"))); // NOI18N
        AddEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpresaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Monto:");

        Monto.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        Monto.setText("jTextField1");
        Monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoActionPerformed(evt);
            }
        });
        Monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MontoKeyReleased(evt);
            }
        });

        Montos.setText("Monto De Empresa");
        Montos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ApellidoVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TelefonoVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(comboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Montos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(NombreVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ApellidoVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TelefonoVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(comboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(AddEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Montos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44))
        );

        AddEmpresa.getAccessibleContext().setAccessibleName("Añadir Empresa");
        Montos.getAccessibleContext().setAccessibleName("Monto De Empresa");

        kGradientPanel1.add(jPanel2);
        jPanel2.setBounds(20, 90, 620, 360);

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Query_35px.png"))); // NOI18N
        jButton2.setText("Consultar Registros");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2);
        jButton2.setBounds(450, 20, 190, 39);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Visitante", new javax.swing.ImageIcon(getClass().getResource("/iconos/Businessman_35px.png")), jPanel1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Visitante");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpresaActionPerformed
        // TODO add your handling code here:

        Empresa2 NU = new Empresa2();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_AddEmpresaActionPerformed

    private void BttGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttGuardar1ActionPerformed
        // TODO add your handling code here:
        mod = DE.Consulta_(cn);
        Guardar(NombreVisitante.getText(), ApellidoVisitante.getText(), TelefonoVisitante.getText(), Monto.getText(), Escritorio.LblId.getText(), mod.get(comboEmpresa.getSelectedIndex()).getId_Empresa(), LugarMonto(), cn);
    }//GEN-LAST:event_BttGuardar1ActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed

        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_LimpiarActionPerformed

    private void comboEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEmpresaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboEmpresaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Consulta_Visitante NU = new Consulta_Visitante();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontoKeyReleased
        // TODO add your handling code here:
        if (comboEmpresa.getSelectedIndex() == 0) {

            if (Double.parseDouble(Monto.getText()) > DE.ConsultaMonto(cn)) {

                JOptionPane.showMessageDialog(null, "Monto De Empresa Insuficiente");
                return;

            }
        }
    }//GEN-LAST:event_MontoKeyReleased

    private void NombreVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreVisitanteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_NombreVisitanteActionPerformed

    private void MontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoActionPerformed

    private void MontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontosActionPerformed
        // TODO add your handling code here:
        if (Montos.isSelected()) {
            Obtener_Monto(comboEmpresa.getSelectedItem().toString());
            Monto.setEnabled(false);
        } else {
            Monto.setEnabled(true);
            Monto.setText("");
        }
    }//GEN-LAST:event_MontosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmpresa;
    private javax.swing.JTextField ApellidoVisitante;
    private javax.swing.JButton BttGuardar1;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextField Monto;
    private javax.swing.JRadioButton Montos;
    private javax.swing.JTextField NombreVisitante;
    private javax.swing.JTextField TelefonoVisitante;
    public static javax.swing.JComboBox comboEmpresa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
