/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Escritorio;

import Citas.Consulta_Cita;
import Citas.Vista_Cita;
import Empresa.Consulta_empresa;
import Empresa.Empresa;
import Usuario.Consulta_Usuario;
import Usuario.RegistroUsuario;
import Vale.Consulta_Vales;
import Vale.Vista_Vales;
import Vehiculo.Consulta_Vehiculo;
import Vehiculo.Vehiculo;
import Visitante.Consulta_Visitante;
import Visitante.Registrar_Visitante;
import Visitas.Historial_Visitas;
import Visitas.Visita;
import static groovy.util.Eval.x;

import java.awt.Image;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Zuly Galicia
 */
public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
        Inicio();
         
        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/IMG/logoo.png"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_AREA_AVERAGING));
        img.setIcon(fondo1);
        this.repaint();
    }

    

    public static void CentrarInternal(JInternalFrame internal) {
        int x = (DeskTop.getWidth() / 2) - (internal.getWidth() / 2);
        int y = (DeskTop.getHeight() / 2) - (internal.getHeight() / 2);
        internal.setLocation(x, y);
    }

    void Inicio() {
        this.setExtendedState(MAXIMIZED_BOTH);
    
        this.dispose();
    }
    public static int use = 1;

    public void Administrador() {
        Archivo.setVisible(true);
        usuario.setVisible(true);
        Archivo.setVisible(true);
        visitante.setVisible(true);
        Empresa.setVisible(true);
        citas.setVisible(true);
         visitas.setVisible(true);
          vale.setVisible(true);
                 

    }

    public void Empleado() {
        Archivo.setVisible(true);
       usuario.setVisible(false);
        Archivo.setVisible(true);
        visitante.setVisible(true);
          Empresa.setVisible(true);
          citas.setVisible(true);
              visitas.setVisible(true);
                vale.setVisible(true);
    }

    public void Ocultar() {
        Archivo.setVisible(true);
         usuario.setVisible(false);
        Archivo.setVisible(true);
        visitante.setVisible(true);
          Empresa.setVisible(true);
          citas.setVisible(true);
           visitas.setVisible(true);
           vale.setVisible(true);
                

    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        DeskTop = new javax.swing.JDesktopPane();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        LblId = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        LblApellido = new javax.swing.JLabel();
        LblRol = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        usuario = new javax.swing.JMenu();
        NuevoUsuario = new javax.swing.JMenuItem();
        ConsultaUsuario = new javax.swing.JMenuItem();
        Empresa = new javax.swing.JMenu();
        AñadirEmpresa = new javax.swing.JMenuItem();
        ConsultaEmpresa = new javax.swing.JMenuItem();
        vehiculo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        visitante = new javax.swing.JMenu();
        AñadirVisitante = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        visitas = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        citas = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        vale = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGENDA SASCIM");
        setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        DeskTop.setToolTipText("");
        DeskTop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        kGradientPanel2.setBackground(new java.awt.Color(42, 245, 152));
        kGradientPanel2.setEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel2.setStartColor(new java.awt.Color(0, 102, 204));
        kGradientPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                Minimizar(evt);
            }
        });

        LblId.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        LblId.setForeground(new java.awt.Color(255, 255, 255));
        LblId.setText("1");
        kGradientPanel2.add(LblId);
        LblId.setBounds(20, 30, 60, 40);

        LblNombre.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        LblNombre.setForeground(new java.awt.Color(255, 255, 255));
        LblNombre.setText("Marta");
        kGradientPanel2.add(LblNombre);
        LblNombre.setBounds(100, 30, 140, 50);

        LblApellido.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        LblApellido.setForeground(new java.awt.Color(255, 255, 255));
        LblApellido.setText("Lopez");
        kGradientPanel2.add(LblApellido);
        LblApellido.setBounds(240, 30, 270, 53);

        LblRol.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        LblRol.setForeground(new java.awt.Color(255, 255, 255));
        LblRol.setText("Administrador");
        kGradientPanel2.add(LblRol);
        LblRol.setBounds(50, 100, 310, 40);

        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kGradientPanel2.add(img);
        img.setBounds(460, 40, 330, 320);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Intervención Municipal");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kGradientPanel2.add(jLabel1);
        jLabel1.setBounds(460, 380, 340, 20);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setText("Sistema De Agua De Ciudad San Cristobal");
        kGradientPanel2.add(jLabel2);
        jLabel2.setBounds(460, 360, 340, 20);

        javax.swing.GroupLayout DeskTopLayout = new javax.swing.GroupLayout(DeskTop);
        DeskTop.setLayout(DeskTopLayout);
        DeskTopLayout.setHorizontalGroup(
            DeskTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
        );
        DeskTopLayout.setVerticalGroup(
            DeskTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );
        DeskTop.setLayer(kGradientPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Archivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Archivo.setText("Archivo");
        Archivo.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        salir.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        salir.setText("salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        Archivo.add(salir);

        jMenuItem10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem10.setText("Cerrar Sesión");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        Archivo.add(jMenuItem10);

        jMenuBar1.add(Archivo);

        usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/User_45px.png"))); // NOI18N
        usuario.setText("Usuario");
        usuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        NuevoUsuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        NuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Add User Male_35px.png"))); // NOI18N
        NuevoUsuario.setText("Nuevo Usuario");
        NuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoUsuarioActionPerformed(evt);
            }
        });
        usuario.add(NuevoUsuario);

        ConsultaUsuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        ConsultaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Find User Male_35px.png"))); // NOI18N
        ConsultaUsuario.setText("Consulta Usuario");
        ConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaUsuarioActionPerformed(evt);
            }
        });
        usuario.add(ConsultaUsuario);

        jMenuBar1.add(usuario);

        Empresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Empresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Company_45px.png"))); // NOI18N
        Empresa.setText("Empresa");
        Empresa.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        AñadirEmpresa.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        AñadirEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/New Company_35px.png"))); // NOI18N
        AñadirEmpresa.setText("Nueva Empresa");
        AñadirEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirEmpresaActionPerformed(evt);
            }
        });
        Empresa.add(AñadirEmpresa);

        ConsultaEmpresa.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        ConsultaEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Query_35px.png"))); // NOI18N
        ConsultaEmpresa.setText("Consulta Empresa");
        ConsultaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaEmpresaActionPerformed(evt);
            }
        });
        Empresa.add(ConsultaEmpresa);

        jMenuBar1.add(Empresa);

        vehiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        vehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Sedan_45px.png"))); // NOI18N
        vehiculo.setText("Vehículo");
        vehiculo.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Car Rental_35px.png"))); // NOI18N
        jMenuItem1.setText("Nuevo Vehículo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        vehiculo.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Car Badge_35px.png"))); // NOI18N
        jMenuItem2.setText("Consulta Vehículos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        vehiculo.add(jMenuItem2);

        jMenuBar1.add(vehiculo);

        visitante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        visitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Account_45px.png"))); // NOI18N
        visitante.setText("Visitante");
        visitante.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        AñadirVisitante.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        AñadirVisitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Manager_35px.png"))); // NOI18N
        AñadirVisitante.setText("Añadir Visitante");
        AñadirVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirVisitanteActionPerformed(evt);
            }
        });
        visitante.add(AñadirVisitante);

        jMenuItem3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Contact Details_35px.png"))); // NOI18N
        jMenuItem3.setText("Consultar Visitantes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        visitante.add(jMenuItem3);

        jMenuBar1.add(visitante);

        visitas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        visitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Waiting Room_45px.png"))); // NOI18N
        visitas.setText("Visitas");
        visitas.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Street View_35px.png"))); // NOI18N
        jMenuItem4.setText("Nueva Visita");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        visitas.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Moleskine_35px.png"))); // NOI18N
        jMenuItem5.setText("Consulta Visitas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        visitas.add(jMenuItem5);

        jMenuBar1.add(visitas);

        citas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Google Calendar_45px.png"))); // NOI18N
        citas.setText("Citas");
        citas.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Calendar Plus_35px.png"))); // NOI18N
        jMenuItem6.setText("Nueva Cita");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        citas.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/To Do_35px.png"))); // NOI18N
        jMenuItem7.setText("Consultar Citas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        citas.add(jMenuItem7);

        jMenuBar1.add(citas);

        vale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Giving Tickets_45px.png"))); // NOI18N
        vale.setText("Vales");
        vale.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/New Ticket_35px.png"))); // NOI18N
        jMenuItem8.setText("Hacer Vale");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        vale.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Two Tickets_35px.png"))); // NOI18N
        jMenuItem9.setText("Consultar Vales");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        vale.add(jMenuItem9);

        jMenuBar1.add(vale);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskTop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskTop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaUsuarioActionPerformed
        // TODO add your handling code here:
        Consulta_Usuario NU = new Consulta_Usuario();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_ConsultaUsuarioActionPerformed

    private void NuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoUsuarioActionPerformed
        // TODO add your handling code here:

        RegistroUsuario NU = new RegistroUsuario();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();

    }//GEN-LAST:event_NuevoUsuarioActionPerformed

    private void AñadirEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirEmpresaActionPerformed
        // TODO add your handling code here:
        Empresa NU = new Empresa();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_AñadirEmpresaActionPerformed

    private void AñadirVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirVisitanteActionPerformed
        // TODO add your handling code here:
        Registrar_Visitante NU = new Registrar_Visitante();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_AñadirVisitanteActionPerformed

    private void ConsultaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaEmpresaActionPerformed
        // TODO add your handling code here:
        Consulta_empresa NU = new Consulta_empresa();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_ConsultaEmpresaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Vehiculo NU = new Vehiculo();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Consulta_Vehiculo NU = new Consulta_Vehiculo();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Consulta_Visitante NU = new Consulta_Visitante();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Visita NU = new Visita();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Historial_Visitas NU = new Historial_Visitas();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        Vista_Cita NU = new Vista_Cita();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        
          Consulta_Cita NU = new Consulta_Cita();
          
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
      
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Vista_Vales NU = new Vista_Vales();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
         Consulta_Vales NU = new Consulta_Vales();
        DeskTop.add(NU);
        CentrarInternal(NU);
        NU.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void Minimizar(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Minimizar
        // TODO add your handling code here:
    }//GEN-LAST:event_Minimizar

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_salirActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
         Login ob = new Login();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem AñadirEmpresa;
    private javax.swing.JMenuItem AñadirVisitante;
    private javax.swing.JMenuItem ConsultaEmpresa;
    private javax.swing.JMenuItem ConsultaUsuario;
    public static javax.swing.JDesktopPane DeskTop;
    private javax.swing.JMenu Empresa;
    public static javax.swing.JLabel LblApellido;
    public static javax.swing.JLabel LblId;
    public static javax.swing.JLabel LblNombre;
    public static javax.swing.JLabel LblRol;
    private javax.swing.JMenuItem NuevoUsuario;
    private javax.swing.JMenu citas;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenu usuario;
    private javax.swing.JMenu vale;
    private javax.swing.JMenu vehiculo;
    private javax.swing.JMenu visitante;
    private javax.swing.JMenu visitas;
    // End of variables declaration//GEN-END:variables
}
